server:
  port: 8080  # ? ?? ?? ??

spring:
  datasource:
    url: jdbc:postgresql://13.209.88.131:5432/study_group  # PostgreSQL ?????? URL
    username: postgres  # ?????? ??? ??
    password: postgres  # ?????? ????
    driver-class-name: org.postgresql.Driver  # JDBC ???? ??? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update  # JPA ??? ?? ?? ??
    show-sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL ?? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace  # Hibernate ?? ??

